
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:${NODE_VERSION:-22.15.0-alpine3.21} 
    working_dir: /app
    volumes:
      - .:/app
      # Anonymous volume:
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    command: ["node", "server.js"]
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  mysql:
    image: mysql:${MYSQL_VERSION:-8.0.27}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "8787:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt

volumes:
  mysql_data:

networks:
  app-network:
