# fly.toml app configuration file generated for backend-ecoride-divine-bird-7975 on 2025-05-23T11:59:47+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-ecoride-divine-bird-7975'
primary_region = 'cdg'

[build]

[env]
  DATABASE_HOST = "ecoride-mysql-internal.internal"
  DATABASE_USER = "studi_ecoride"
  DATABASE_PASSWORD = "123Kevazingo"
  DATABASE_NAME = "ecoride_db"
  DATABASE_PORT = "3306"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared' 
  cpus = 1
